name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.0.1'
      SERVERPOD_PASSWORD_database: '4jm4wRnXtwFyd4SFX3YxNP7-mTWfF5MO'
      SERVERPOD_PASSWORD_redis: 'dq2SjAOB56tK-5QzC6jEGYnyzYf1fLUa'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: clcosu_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: clcosu_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: clcosu_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: clcosu_server
        run: serverpod generate

      - name: Run tests
        working-directory: clcosu_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: clcosu_server
        run: docker compose down -v
